### ISSUE TITLE
Border has a dodge/screen shader effecti going on with opengl enabled.

### ISSUE THREAD

**Issue by onodera-punpun** [naelstrof/slop#59] opened 2017-02-23 20:53 UTC
I just want the slop border to be a solid color, but right now it uses some kind of dodge or screen shader.

**Comment by naelstrof** [comment] 2017-02-23 20:55
Could you screenshot the issue?

If you're not using the --shader flag, it should be a solid color.

**Comment by naelstrof** [comment] 2017-02-23 20:59
It would help if you named your compositor, and video card. As well as posting the output of slop (if any).

**Comment by onodera-punpun** [comment] 2017-02-23 21:11
https://sr.ht/50er.png

It should all be pink, but only on darker backgrounds it's kind of pink now.

Compositor: Compoton with xrender backend, nvidia used for vsync.

Video card: nvidia GTX 570 with the newest nvidia short lived branch driver.

Command used: ```fish
maim -b 10 -p -10 -c 0.921,0.376,0.517,1 -q $argv $d/scrot(math (ls $d | grep -c 'scrot[0-9]*.png') + 2).png
```

Output: none

**Comment by naelstrof** [comment] 2017-02-23 21:17
Does `slop -b10 -p-10 -c0.921,0.376,0.517,1` cause the same problem without printing any warnings?
I'd like to point out that you've added the --quiet flag so you might not see any with maim either.

**Comment by naelstrof** [comment] 2017-02-23 21:18
I think what might be wrong is that slop's window is getting pushed to the back. There's some things I can do to prevent this.

**Comment by onodera-punpun** [comment] 2017-02-23 21:20
Same problem, without warnings, yeah I removed -q when testing for output before.

**Comment by naelstrof** [comment] 2017-02-23 21:26
Ok. Could you try the new release? I set the appropriate atom now to tell the window manager to keep slop on top of all the other windows. https://github.com/naelstrof/slop/commit/e787f1b15a9f5a19ed554d94621ccc0db1884402

**Comment by onodera-punpun** [comment] 2017-02-23 21:29
Same problem... I think it does not have something to do with it being below other windows, but an actual shader issue somehow, here is a better example: https://sr.ht/7UUy.png

**Comment by naelstrof** [comment] 2017-02-23 21:41
Ah yeah, that's definitely bad color blending.

Try this one? https://github.com/naelstrof/slop/commit/9df78697d9dec4fc81caec58129439a88d2829c7

**Comment by onodera-punpun** [comment] 2017-02-23 21:49
Nope :(, exactly the same

**Comment by naelstrof** [comment] 2017-02-23 21:52
I'm going to have to replicate the issue. Which DE/WM are you using?

**Comment by onodera-punpun** [comment] 2017-02-23 21:54
The newest openbox with 10px width `#EEEEEE` borders. Xorg 1.19.1, nvidia 378-13, compton git master (the release hasn't been touched in years).

**Comment by naelstrof** [comment] 2017-02-23 21:57
Thanks, I'll get to work on it. Though first I'll add a flag to disable OpenGL mode. I was hoping to avoid it, but some configurations just don't like transparent OpenGL windows.

**Comment by onodera-punpun** [comment] 2017-02-23 22:20
Fixed it 👍, should I leave this issue open but change the title to "without -o flag"?

**Comment by naelstrof** [comment] 2017-02-23 22:30
Sounds good. I updated maim to accept -o as well. I'll keep you posted on progress.

**Comment by naelstrof** [comment] 2017-02-24 03:31
Good news, I got it to break on my desktop. It turns out specifically that Nvidia is the cause. I'm working on a solution now.

**Comment by naelstrof** [comment] 2017-02-24 07:57
Fixed in https://github.com/naelstrof/slop/releases/tag/v5.3.27 
Unfortunately I had to pull in XRender as a dependency again because of this bug, not that big of a deal though.

Please use the graphics acceleration where possible. Also you might want to look at the --highlight option, I've changed it a bit and you might like it.

**Closed by naelstrof** 2017-02-24 07:57 UTC

**Comment by onodera-punpun** [comment] 2017-02-24 17:30
This indeed fixed it, thanks! 👍 

I have to say thought, with the `-o` flag slop starts noticeably faster, so I'd really like it if you kept the flag :)

**Comment by naelstrof** [comment] 2017-02-24 18:55
Good to know, you might want to check to make sure you're compiling slop in Release mode. I don't have any perceptible startup speed differences on my machine.

**Comment by onodera-punpun** [comment] 2017-02-24 21:23
Right now I'm just building with `cmake -DCMAKE_INSTALL_PREFIX="/usr" ./`, should I add any more flags?

**Comment by naelstrof** [comment] 2017-02-24 21:43
`cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ./` would give you a huge speedup since it compiles with compiler optimizations.

I should probably add that to the README.
